config/routes.rb
Scrapbook::Application.routes.draw do

  devise_for :users
  resources :users do
    get 'welcome', :action => :welcome, :on => :member
    get 'invitation', :action => :invitation, :on => :member
  end
  match 'welcome' => 'users#welcome', :as => :welcome

  resources :scraps do
    resources :uploads
    resources :reactions
    resources :taggings, :only => :new
    get :chart, :on => :member, :as => "chart"
    get :discussion, :on => :collection, :as => "discussion"
    get :help, :on => :collection, :as => "help"
  end
  
  resources :tags, :only => :index
  resources :taggings, :only => :new
  resources :reactions
  root :to => 'scraps#index'
  
  match '/suggestions', :to => 'suggestions#index'
  match '/suggestions/:type', :to => 'suggestions#index'

end

app/controllers/reactions_controller.rb
class ReactionsController < ScrapbookController
  respond_to :html, :js, :json
  
  before_filter :require_active_user, :only => [:new, :create]
  before_filter :get_all_reactions, :only => [:index]
  before_filter :build_reaction, :only => [:new, :create]
  before_filter :set_reaction, :only => [:update, :create]
  
  def index
    respond_with @scraps
  end
  
  def create
    @scrap = @reaction.scrap
    respond_with @reaction do |format|
      format.js { render :partial => 'reactions/react' }
    end
  end
  
protected

  def get_all_reactions
    @scraps = Scrap.with_reactions
  end
  
  def build_reaction
    @scrap = Scrap.find(params[:scrap_id])
    @reaction = @scrap.reactions.build
  end

  def set_reaction
    @reaction.update_attributes(params[:reaction])
  end

end

app/helpers/reactions_helper.rb
module ReactionsHelper
end

app/views/reactions/_react.html.haml
- scrap ||= @scrap

- if current_user.observer?
  #reacted
    .minichart{:rel => "#{chart_scrap_url(@scrap)}.json"}
      %canvas#axis
    .summary
      %h4
        Average reaction
      %p
        Us
        %strong
          = scrap.average_score_for('usness')
        Like: 
        %strong
          = scrap.average_score_for('affection')
  

- elsif @reaction
  #reacted
    .minichart{:rel => "#{chart_scrap_url(@scrap)}.json"}
      %canvas#axis
    .summary
      %h4
        Your reaction
      %p
        Us
        %strong
          = @reaction.score_for('usness')
        Like: 
        %strong
          = @reaction.score_for('affection')
      %h4
        Average reaction
      %p
        Us
        %strong
          = scrap.average_score_for('usness')
        Like: 
        %strong
          = scrap.average_score_for('affection')
        
- else

  - reaction = current_user.reactions.build(:scrap => @scrap)
  = form_for [@scrap, reaction], :id => "new_reaction" do |f|

    - Scale.all.each do |scale|
      - score = reaction.scores.build(:scale => scale)
      = f.fields_for :scores, score do |sf|
        = sf.hidden_field :scale_id
        %p.slider
          = sf.label :value, scale.min_label
          = sf.range_field :value, :class => "slider", :"data-values" => "", :default => 0, :max => 10, :min => -10
          = sf.label :value, scale.max_label
    .controls.small
      %p
        = f.submit t :show_reactions
    

app/views/reactions/index.html.haml
#reactions.bigchart{:rel => "#{reactions_url}.json"}
  %canvas#axis
  .xmin
    Not us
  .xmax
    Us
  .ymin
    Don't like
  .ymax
    Like