config/routes.rb
Scrapbook::Application.routes.draw do

  devise_for :users
  resources :users do
    get 'welcome', :action => :welcome, :on => :member
    get 'invitation', :action => :invitation, :on => :member
  end
  match 'welcome' => 'users#welcome', :as => :welcome

  resources :scraps do
    resources :uploads
    resources :reactions
    resources :taggings, :only => :new
    get :chart, :on => :member, :as => "chart"
    get :discussion, :on => :collection, :as => "discussion"
    get :help, :on => :collection, :as => "help"
  end
  
  resources :tags, :only => :index
  resources :taggings, :only => :new
  resources :reactions
  root :to => 'scraps#index'
  
  match '/suggestions', :to => 'suggestions#index'
  match '/suggestions/:type', :to => 'suggestions#index'

end

app/models/scrap.rb
class Scrap < ActiveRecord::Base
  belongs_to :user
  has_many :reactions
  has_many :scores, :through => :reactions
  has_many :taggings, :dependent => :destroy
  has_many :tags, :through => :taggings, :uniq => true
  has_upload :image, 
             :geometry => "960x720#",
             :styles => {
               :icon => "48x48#",
               :thumb => "100x100#",
               :list => "230x174#",
               :precrop => "1600x1200^"
             }

  attr_accessor :scrap_type
  attr_accessible :user_id, :name, :body, :image, :youtube_id, :image_offset_left, :image_offset_top, :image_upload_id, :image_scale_width, :image_scale_height, :description, :scrap_type, :taggings_attributes, :tags_attributes
  accepts_nested_attributes_for :tags, :allow_destroy => true, :reject_if => :all_blank
  accepts_nested_attributes_for :taggings, :allow_destroy => true, :reject_if => :all_blank
  
  scope :with_reactions, select("scraps.*").joins("LEFT OUTER JOIN reactions on reactions.scrap_id = scraps.id").group("scraps.id").having("count(reactions.scrap_id) > 0")
  
  before_save :record_creator
  before_save :combine_texts
  
  scope :matching, lambda { |fragment| 
    fragment = "%#{fragment}%"
    where('scraps.combined_text like ?', fragment)
  }
  
  scope :tagged_with, lambda { |tag|
    tag = Tag.find_by_name(tag) unless tag.is_a?(Tag)
    select("scraps.*").joins("INNER JOIN taggings as tt on tt.scrap_id = scraps.id").where(["tt.tag_id = ?", tag]) if tag
  }

  # The *tagged_with_any_of* scope is a join on the taggings table that returns every scrap tagged with any of the given tags.
  #
  scope :tagged_with_any_of, lambda { |tags|
    placeholders = tags.map{'?'}.join(',')
    select("scraps.*").joins("INNER JOIN taggings as tt on tt.scrap_id = scraps.id").where(["tt.tag_id in(#{placeholders})"] + tags.map(&:id)).group("scraps.id").order("count(tt.id) DESC")
  }

  # The *tagged_with_all_of* scope is a join on the taggings table that returns every scrap tagged with all of the given tags.
  # It does this with an extra `having` clause requiring that the number of tagging records should equal the number of tags specified,
  # so it's possible to be wrong if we are tagged many times with the same tag, but that shouldn't happen.
  #
  scope :tagged_with_all_of, lambda { |tags|
    placeholders = tags.map{'?'}.join(',')
    tag_count = tags.size
    select("scraps.*").joins("INNER JOIN taggings as tt on tt.scrap_id = scraps.id").where(["tt.tag_id in(#{placeholders})"] + tags.map(&:id)).group("scraps.id").having("count(tt.id) = #{tag_count}")
  }
  
  def video?
    youtube_id?
  end

  def average_score_for(scale)
    scale = Scale.find_by_name(scale) unless scale.is_a? Scale
    scores = self.scores.on_scale(scale)
    total = 0
    unless scores.empty?
      count = scores.count
      scores.each do |score|
        unless score.value == nil 
          total += score.value
        else
          count -= 1
        end
      end
      unless count == 0
        (total/count).round(3)
      else
        "none yet"
      end
    else
      "none yet"
    end
  end

  # This will get more complicated
  def type
    if new_record? || image?
      'image'
    elsif video?
      'video'
    else
      'text'
    end
  end
  
  def wordiness
    if body.length < 48
      'word'
    elsif body.length < 320
      'phrase'
    elsif body.length < 800
      'paragraph'
    else
      'text'
    end
  end
  
  def text_size
    if l = body.length
      ((600.0/(l+100.0)) + 0.25) / 1.5
    else
      1
    end
  end
  
  def as_json(options={})
    count = reactions.count
    json = {
      :id => id,
      :name => name,
      :size => count,
      :type => type,
      :wordiness => wordiness,
      :text => body,
      :thumb => image.url(:thumb),
      :image => image.url(:cropped),
      :user => user.as_json(options)
    }
    scores.compact.each do |score|
      json[score.scale.name] ||= 0
      json[score.scale.name] += score.value/count if score.value
    end
    json
  end

protected

  def record_creator
    self.user ||= User.current
  end
  
  def combine_texts
    texts = [name, body, image_file_name] + tags.map(&:name)
    self.combined_text = texts.join(' ').searchable
  end

end

app/controllers/scraps_controller.rb
class ScrapsController < ScrapbookController
  respond_to :html, :js, :json
  
  before_filter :authenticate_user!
  before_filter :require_active_user, :except => [:index, :show]
  before_filter :find_scraps, :only => [:index]
  before_filter :get_scrap, :only => [:show, :edit, :update, :destroy, :chart]
  before_filter :require_permission, :only => [:edit, :update, :destroy]
  before_filter :build_scrap, :only => [:new, :create]
  before_filter :update_scrap, :only => [:create, :update]

  def index
    respond_with(@scraps) do |format|
      format.js { render :partial => 'scrap_list' }
    end
  end
  
  def discussion
    render
  end

  def help
    render
  end

  def show
    @reaction = current_user.reaction_to(@scrap).first()
    respond_with(@scrap)
  end

  def edit
    respond_with(@scrap)
  end

  def update
    respond_with(@scrap)
  end

  def create
    respond_with(@scrap)
  end
  
  def chart
    @reactions = @scrap.reactions
    respond_with(@reactions)
  end
  
  def destroy
    @scrap.destroy
    flash[:notice] = t(:scrap_destroyed, :name => @scrap.name)
    redirect_to scraps_url
  end

protected

  def require_permission
    render :text => "That's not yours!", :status => :forbidden unless current_user.can_edit?(@scrap)
  end

  def find_scraps
    sorts = {
      :name => 'ASC',
      :updated_at => 'DESC',
      :created_at => 'DESC'
    }
    @by = params[:by] || 'date'
    @by = 'created_at' unless sorts[@by.to_sym]
    @order = params[:order] || sorts[@by.to_sym] || 'ASC'
    
    @scraps = Scrap.order("scraps.#{@by} #{@order}")
    @tags = [params[:tag]].flatten.map{|t| Tag.find_by_name(t) }.compact
    @fragments = []
    
    unless params[:q].blank?
      [params[:q]].flatten.reject(&:blank?).each do |fragment|
        if scrap = Scrap.find_by_name(fragment)
          @scraps.push(scrap)
        elsif tag = Tag.find_by_name(fragment)
          @tags.push(tag)
        else
          @fragments += fragment.split(/\s+/)
        end
      end
    end
    
    # @rejected_fragments = @fragments.select {|frag| STOPWORDS.include?(frag) }
    # @fragments = (@fragments - @rejected_fragments).compact.uniq
    @scraps = @scraps.tagged_with_all_of(@tags) if @tags.any?
    @fragments.each { |frag| @scraps = @scraps.matching(frag) }

    @show = params[:show] || 20
    @page = params[:page] || 1
    @scraps = @scraps.page(@page).per(@show) unless @show == 'all'
  end

  def get_scrap
    @scrap = Scrap.find(params[:id])
  end

  def build_scrap
    @scrap = Scrap.new
  end
  
  def update_scrap
    if params[:scrap][:scrap_type] == 'image'
      params[:scrap][:body] = ""
    else
      params[:scrap][:image_upload_id] = nil
    end
    @scrap.update_attributes(params[:scrap])
  end

end

app/helpers/scraps_helper.rb
module ScrapsHelper
end

app/views/scraps/_form.html.haml
= form_for @scrap do |f|
  #body
    .panel.image
      .dropbox{:rel => uploads_path(:format => :js)}
        .img
          - if @scrap.image_upload
            = link_to image_tag(@scrap.image.url(:cropped)), edit_upload_url(@scrap.image_upload, :scrap_id => @scrap.id), :class => 'recrop'
          - else 
            .nonie
              = link_to image_tag(@scrap.image.url(:cropped)), new_upload_url(:scrap_id => @scrap.id), :class => 'picker'
            .ie
              = image_tag(@scrap.image.url(:cropped))
        - unless @scrap.image?
          %p.instructions.nonie
            %span.droppable
              = t :image_note_drop
            = t(:image_note)
          %p.instructions.ie
            %br
            = t :image_note_ie

        %h2.waiter
          = t :please_wait

        .controls
          .cancel
            = link_to t(:cancel), '#'
            
        %p.file
          = file_field_tag :image_uploader, :class => 'file', :id => 'file_upload', :accept => "image"
    
    .panel.text
      = f.text_area :body, :rel => Scrap.human_attribute_name("body"), :class => 'labelled body'

    .panel.video
      .youtube_picker
        %p
          = f.label :youtube_id
          %br
          = f.text_field :youtube_id
          %br
          %span.note
            = t :youtube_id_note
        
    .panel.audio
    .panel.document
  #caption
    .tabs
      = link_to t(:document), '#document', :class => 'unavailable', :'data-reveal' => 'div.document'
      = link_to t(:audio), '#audio', :class => 'unavailable', :'data-reveal' => 'div.audio'
      = link_to t(:video), '#video', :class => 'tab', :'data-reveal' => 'div.video'
      = link_to t(:text), '#text', :class => 'tab', :'data-reveal' => 'div.text'
      = link_to t(:image), '#image', :class => 'tab here', :'data-reveal' => 'div.image'
      = f.hidden_field :scrap_type, :class => 'tabbed', :value => @scrap.type
  
    #metadata
      %h2
        = f.text_field :name, :rel => Scrap.human_attribute_name("name"), :class => 'labelled name'
      %p
        = f.text_area :description, :rel => Scrap.human_attribute_name("description"), :class => 'labelled description'

      - if current_user.admin?
        %p
          = f.label :user_id
          %br
          = f.select :user_id, User.for_selection
    .controls
      %p
        = f.submit t :save_scrap

    #tags
      %ul.tagger
        - @scrap.tags.each do |tag|
          %li.remove
            = f.fields_for :tags, tag, :child_index => tag.id do |tf|
              = link_to tag.name, '#', :class => 'detag'
              = tf.hidden_field :_destroy, :class => 'destroy'

        %li.add{:rel => new_tagging_url(:scrap_id => @scrap.id)}
          %span.newtag
            = f.fields_for :tags, @scrap.tags.build do |tf|
              = tf.text_field :name, :rel => "add tag", :class => 'labelled', :autocomplete => 'off'
              = link_to '&nbsp;'.html_safe, '#', :class => 'tag add_tag'
        
      %p.note
        = t :form_tags_note
    

app/views/scraps/_scrap.html.haml
%a{:href => scrap_url(scrap), :class => "scrap_link", :id => "scrap_#{scrap.id}"}
  .scrap{:class => scrap.wordiness}
    - if scrap.video?
      .thumbnail{:style => "background-image: url('http://img.youtube.com/vi/#{scrap.youtube_id}/default.jpg')"}
        .playable
    - elsif scrap.image?
      = image_tag(scrap.image.url(:list))
    - else
      - if scrap.wordiness == 'text' || scrap.wordiness == 'paragraph'
        %p.sweet-justice{:style => "font-size: #{"%.2f" % scrap.text_size}em"}
          = strip_tags(scrap.body)
      - else
        %p.sweet-hyphens{:style => "font-size: #{"%.2f" % scrap.text_size}em"}
          = strip_tags(scrap.body)
    

app/views/scraps/_scrap_list.html.haml
#scraps
  - if @scraps.any?
    = render :partial => "scrap", :collection => @scraps

    .pagination
      = paginate @scraps, :params => {:format => nil}
  
  - else
    .nomatch
      %h2
        = t :sorry_no_matches

app/views/scraps/chart.html.haml
= @scrap.reactions.collect{ |r| r.as_json }

app/views/scraps/discussion.html.haml
#discussion
  %h1.pagetitle
    = t :collected_discussion

  #latest_posts
    %h2.waiting
      = t :messages_loading

app/views/scraps/edit.html.haml
#scrap.editing
  = render :partial => 'form'

app/views/scraps/help.en.html.haml
#discussion
  %h1.pagetitle
    = t :help!

  %p
    The scrapbook has three purposes: to gather raw material, to help us to sift through it, and to allow people to hang out together in a context furnished with ideas.
    Its eventual goal is to arrive at an identity firmly rooted in your thinking and your aesthetic preferences. Its fond hope is that in the process you will become a more tightly knit group.
    
  %p
    There are three things you can do here: add material, give your reactions and add comments. A fourth will become apparent this week.
    
  %h2
    How to add material
  
  %p
    Click on 'Add scrap' in the masthead and a blank scrap will appear. 
  %p
    %strong
      To add an image, 
    click in the grey area (or in Firefox, you can just drop a picture there). 
    When your file has uploaded, a cropping and scaling interface will appear so that you can adjust the presentation of your image on the page. 
    Drag the image to change its crop, and drag the slider to change its size.
  %p
    %strong
      To add text,
    click on the 'text' tab just below the grey upload area and it will turn into a large text box. Type or paste your text in there. 
    Single carriage returns will be preserved as line breaks. Double returns will show as new paragraphs. No other formatting is supported: it's the text we're interested in.
  %p
    Video and audio are going to be supported soon, but perhaps not this week.
    
  %h2
    What material to add?
    
  %p
    That's broadly up to you, but keep in mind the purpose of the site:
    material is useful if it stimulates discussion, clarifies a point, captures a view or proposes a consensus. 
    Any of those things can be done directly or obliquely, and the image that seems just right is just as useful as the text.

  %p
    In the end, all we really need are a few key fragments that capture the ethos and feeling of the group. 
    We will need to spread out before we can converge on those few. How far, we will find out.
  
  %h2
    Reactions are anonymous
    
  %p
    Whenever you first visit a scrap, you will see the thing itself and two reaction sliders. 
    No other context will be visible until you use the two sliders to give your immediate reaction. Be quick and candid. The 
    %strong
      Like &larr;&rarr; Dislike
    scale is for your personal reaction. The 
    %strong
      Us &larr;&rarr; Not us
    scale is for your sense of whether this is right for the group. Click on the 'show reactions' button to record your reaction and see those of other poeple.
    
  %h2
    Discussion is the point
  %p
    Having reacted, you can join the discussion around that scrap. Here your remarks are credited and this is where we hope to see real progress. Please take part.

app/views/scraps/index.html.haml
- if @tags.any?
  .facets
    = t :scraps_tagged_with
    - @tags.each do |tag|
      = link_to tag.name, scraps_path, :class => 'detag'

= render :partial => "scraps/scrap_list"

app/views/scraps/new.html.haml
#scrap.editing
  = render :partial => 'form'

app/views/scraps/show.html.haml
- visible = true if current_user.observer? || @reaction

#scrap{:class => @scrap.type}
  #body
    - if @scrap.video?
      %iframe.youtube{:width => "960", :height => "720", :src => "http://www.youtube.com/embed/#{@scrap.youtube_id}?fs=1&autohide=1&modestbranding=1&autoplay=1&wmode=opaque", :frameborder => 0, :allowfullscreen => true}
        
    - elsif @scrap.image?
      .image
        = image_tag @scrap.image.url(:cropped)
    
    - elsif @scrap.body?
      - if @scrap.wordiness == 'text' || @scrap.wordiness == 'paragraph'
        %div.text.sweet-justice{:style => "font-size: #{"%.2f" % (@scrap.text_size * 2)}em"}
          = simple_format(@scrap.body)
      - else
        %div.text.sweet-hyphens{:style => "font-size: #{"%.2f" % (@scrap.text_size * 2)}em"}
          = simple_format(@scrap.body)

    - if current_user.can_edit?(@scrap)
      #admin
        = link_to "edit", edit_scrap_url(@scrap), :class => 'edit'
        = link_to "delete", scrap_url(@scrap), :method => "delete", :class => 'delete', :confirm => t(:confirm_delete_scrap, :name => @scrap.name)

  #caption
    #reaction
      = render :partial => 'reactions/react', :@scrap => @scrap

    #metadata{:class => visible ? "" : "hide_until_reaction"}
      %h2
        = @scrap.name
      - if @scrap.description?
        = simple_format @scrap.description
          
      - if @scrap.user
        %p.note
          = t :uploaded_by
          = @scrap.user.forename

    #tags{:class => visible ? "" : "hide_until_reaction"}
      %ul.tags
        - @scrap.tags.each do |tag|
          %li
            = link_to tag.name, scraps_path(:tag => tag.name), :class => 'tag'
      %p
    
      
      
  - if visible
    #discussion
      #disqus_thread
      = javascript_include_tag "http://scrapbok.disqus.com/embed.js"