config/routes.rb
Scrapbook::Application.routes.draw do

  devise_for :users
  resources :users do
    get 'welcome', :action => :welcome, :on => :member
    get 'invitation', :action => :invitation, :on => :member
  end
  match 'welcome' => 'users#welcome', :as => :welcome

  resources :scraps do
    resources :uploads
    resources :reactions
    resources :taggings, :only => :new
    get :chart, :on => :member, :as => "chart"
    get :discussion, :on => :collection, :as => "discussion"
    get :help, :on => :collection, :as => "help"
  end
  
  resources :tags, :only => :index
  resources :taggings, :only => :new
  resources :reactions
  root :to => 'scraps#index'
  
  match '/suggestions', :to => 'suggestions#index'
  match '/suggestions/:type', :to => 'suggestions#index'

end

app/views/layouts/_search_form.html.haml
#searchform.fast
  %form{:action => scraps_url, :id => 'scrap_search', :"data-remote" => true}
    = form_tag do
      = text_field_tag(:q, params[:q], :placeholder => "search", :class => 'search', :type => 'search')

app/views/layouts/application.html.haml
!!!
%html{:lang => 'en'}
  %head
    %title
      = t(:scrapbook)
      - if content_for?(:pagetitle)
        ✁
        = content_for(:pagetitle)

    = stylesheet_link_tag "http://fast.fonts.com/cssapi/39788b9e-bfde-4f08-a9c5-5b2c08e0c676.css"
    = stylesheet_link_tag "application"
    = javascript_include_tag "application"
    = content_for :head
    = csrf_meta_tags

%body
  #container
    #header
      %h1
        = link_to t(:scrapbook), "/"
      - if user_signed_in?
        #nav.navigation
          %p
            = link_to t(:latest), scraps_url, :class => 'latest'
            = link_to t(:discussion), discussion_scraps_url, :class => 'discussion'
            = link_to t(:tags), tags_url, :class => 'tags'
            = link_to t(:overview), reactions_url, :class => 'chart'
            = link_to t(:add_scrap), new_scrap_url, :class => 'add' unless current_user.passive_observer?
    
    #content
      = yield

    - if user_signed_in?
      #footer.navigation
        %p
          = t :signed_in_as, :name => current_user.name
          = link_to t(:scrap_help), help_scraps_url, :class => 'help'
          = link_to t(:invite), new_user_url, :class => 'invite'
          = link_to t(:preferences), edit_user_url(current_user), :class => 'preferences'
          = link_to t(:log_out), destroy_user_session_path, :class => 'logout', :method => :delete
        = render 'layouts/search_form'

    #colophon
      = t(:footer_info).html_safe


  #flashes
    %p.notice= notice
    %p.alert= alert

  :javascript
    var _gaq=[['_setAccount','UA-15051397-11'],['_trackPageview']];
    (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
    g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
    s.parentNode.insertBefore(g,s)}(document,'script'));

app/views/layouts/email.html.haml
!!!
%html{:lang => 'en'}
  %head
    %title
      = @subject
  %body{:style => "margin: 50px; font-family: 'Georgia, Baskerville, serif; font-size: 1.5em; line-height: 1.5;"}
    #page{:style => "margin: 30px 40px 20px 62px;"}
      #content
        = yield